// GENERATED by scripts/build-client.mjs — edit lib/core.js or src/ui.js instead.
window.__ModuleLoader__.load({
  id: "dsh-meter",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const React = require("react");
    const ReactDOM = require("react-dom");

/**
 * dsh-meter core — the official DeepSeek rate card, the time-of-use clock, and
 * the pure cost fold.
 *
 * This module is the single source of both halves: the host plugin imports it,
 * and `scripts/build-client.mjs` inlines this exact file into the browser
 * bundle. A price never exists in two places.
 *
 * Money is computed from provider-reported token counts, so it is an estimate
 * of what DeepSeek will bill, not the invoice. The three billed buckets are
 * disjoint by the harness `TokenUsage` convention: `inputTokens` is
 * cache-MISS input (the DeepSeek adapter subtracts hits out of `prompt_tokens`),
 * `cacheReadTokens` is cache-HIT input, and `outputTokens` already contains
 * reasoning tokens.
 */

/* ------------------------------------------------------------------ *
 * PRICING-TABLE-START — verbatim from
 * https://api-docs.deepseek.com/quick_start/pricing (fetched 2026-08-13).
 * Units: currency per 1M tokens. USD is the international platform's table
 * and CNY the mainland platform's — they are separate published tables, not
 * an exchange-rate conversion of each other.
 * ------------------------------------------------------------------ */

/** Time-of-use billing begins at 16:00 UTC on 2026-08-16 (00:00 Beijing, Aug 17). Before it, one flat rate applies all day. */
const TIME_OF_USE_FROM = Date.UTC(2026, 7, 16, 16, 0, 0)

/**
 * Peak windows as `[startHourUtc, endHourUtc)` pairs — 01:00-04:00 and
 * 06:00-10:00 UTC (09:00-12:00 and 14:00-18:00 Beijing). Every other hour is
 * off-peak, including the two-hour 04:00-06:00 gap between the windows.
 */
const PEAK_WINDOWS_UTC = [[1, 4], [6, 10]]

/**
 * Published rates per 1M tokens, by model, tariff, and currency.
 * `hit` = cache-hit input, `miss` = cache-miss input, `out` = output.
 */
const RATES = {
  'deepseek-v4-flash': {
    flat: { usd: { hit: 0.0028, miss: 0.14, out: 0.28 }, cny: { hit: 0.02, miss: 1, out: 2 } },
    offpeak: { usd: { hit: 0.007, miss: 0.22, out: 0.66 }, cny: { hit: 0.05, miss: 1.5, out: 4.5 } },
    peak: { usd: { hit: 0.014, miss: 0.44, out: 1.32 }, cny: { hit: 0.1, miss: 3, out: 9 } },
  },
  'deepseek-v4-pro': {
    flat: { usd: { hit: 0.003625, miss: 0.435, out: 0.87 }, cny: { hit: 0.025, miss: 3, out: 6 } },
    offpeak: { usd: { hit: 0.022, miss: 0.66, out: 1.98 }, cny: { hit: 0.15, miss: 4.5, out: 13.5 } },
    peak: { usd: { hit: 0.044, miss: 1.32, out: 3.96 }, cny: { hit: 0.3, miss: 9, out: 27 } },
  },
}
/* PRICING-TABLE-END */

/** Tariffs in display order; `flat` is the pre-time-of-use single rate. */
const TARIFFS = ['flat', 'offpeak', 'peak']

/** Currency symbols for the two published tables. */
const CURRENCY_SYMBOL = { usd: '$', cny: '¥' }

/**
 * The tariff a request dispatched at `epochMs` is billed under.
 * @param {number} epochMs - request dispatch time.
 * @returns {'flat'|'peak'|'offpeak'} the tariff in force at that instant.
 */
function tariffAt(epochMs) {
  if (epochMs < TIME_OF_USE_FROM) return 'flat'
  const hour = new Date(epochMs).getUTCHours()
  for (const [start, end] of PEAK_WINDOWS_UTC) if (hour >= start && hour < end) return 'peak'
  return 'offpeak'
}

/**
 * When the tariff next changes, and to what. Before the switchover the answer
 * is the switchover itself — that is the next change a user can act on.
 * @param {number} epochMs - the instant to look forward from.
 * @returns {{ tariff: string, next: string, at: number }} current tariff, the one that follows, and when it starts.
 */
function nextTariffChange(epochMs) {
  const tariff = tariffAt(epochMs)
  if (epochMs < TIME_OF_USE_FROM) {
    return { tariff, next: tariffAt(TIME_OF_USE_FROM), at: TIME_OF_USE_FROM }
  }
  const hourMs = 3_600_000
  const dayStart = Math.floor(epochMs / (24 * hourMs)) * 24 * hourMs
  const boundaries = []
  for (const [start, end] of PEAK_WINDOWS_UTC) boundaries.push(start, end)
  boundaries.sort((a, b) => a - b)
  for (const hour of boundaries) {
    const at = dayStart + hour * hourMs
    if (at > epochMs) return { tariff, next: tariffAt(at), at }
  }
  // Past the last boundary of the UTC day: the next change is the first one tomorrow.
  const at = dayStart + 24 * hourMs + boundaries[0] * hourMs
  return { tariff, next: tariffAt(at), at }
}

/**
 * The published schedule itself: 24 UTC hours labelled peak or off-peak, for
 * the clock strip. Independent of the switchover date — before it the strip
 * shows the schedule that is about to apply, which is exactly what a user
 * planning the next hour needs to see.
 * @returns {string[]} 24 tariff names, index = UTC hour.
 */
function tariffSchedule() {
  const hours = []
  for (let hour = 0; hour < 24; hour++) {
    hours.push(PEAK_WINDOWS_UTC.some(([start, end]) => hour >= start && hour < end) ? 'peak' : 'offpeak')
  }
  return hours
}

/** Whether a model id has a published rate. */
const isPriced = model => Object.prototype.hasOwnProperty.call(RATES, model)

/**
 * Cost of one token bucket set under one tariff.
 * @param {{miss: number, hit: number, out: number}} tokens - billed token counts.
 * @param {string} model - provider model id.
 * @param {string} tariff - tariff key.
 * @param {string} currency - `usd` or `cny`.
 * @returns {number} cost in the currency's units, 0 for an unpriced model.
 */
function costOf(tokens, model, tariff, currency) {
  const split = bucketCostOf(tokens, model, tariff, currency)
  return split.miss + split.hit + split.out
}

/**
 * The same cost, kept split by billed bucket — what the breakdown rows show.
 * @param {{miss: number, hit: number, out: number}} tokens - billed token counts.
 * @param {string} model - provider model id.
 * @param {string} tariff - tariff key.
 * @param {string} currency - `usd` or `cny`.
 * @returns {{miss: number, hit: number, out: number}} cost per bucket, all zero for an unpriced model.
 */
function bucketCostOf(tokens, model, tariff, currency) {
  const rate = RATES[model]?.[tariff]?.[currency]
  if (rate === undefined) return { miss: 0, hit: 0, out: 0 }
  return {
    miss: (tokens.miss * rate.miss) / 1_000_000,
    hit: (tokens.hit * rate.hit) / 1_000_000,
    out: (tokens.out * rate.out) / 1_000_000,
  }
}

/* ------------------------------------------------------------------ *
 * The fold: session log -> billed token buckets.
 * ------------------------------------------------------------------ */

const zero = () => ({ miss: 0, hit: 0, out: 0, requests: 0 })

const add = (target, sample, requests) => ({
  miss: target.miss + sample.miss,
  hit: target.hit + sample.hit,
  out: target.out + sample.out,
  requests: target.requests + requests,
})

/**
 * The three billed buckets of one usage report. A `cacheWriteTokens` count
 * (never reported by the DeepSeek adapter, possible from another) joins the
 * cache-miss bucket: DeepSeek publishes no separate write price and bills a
 * first-time prompt at the miss rate.
 * @param {object} usage - harness `TokenUsage`.
 * @returns {{miss: number, hit: number, out: number}} billed token counts.
 */
function billedTokens(usage) {
  const number = value => (typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : 0)
  return {
    miss: number(usage.inputTokens) + number(usage.cacheWriteTokens),
    hit: number(usage.cacheReadTokens),
    out: number(usage.outputTokens),
  }
}

/** Initial fold state for an empty log. */
const init = () => ({ bills: {}, last: null, step: null, route: null, firstAt: null, lastAt: null })

/** The usage a chunk or a finalized assistant message reports, if any. */
const usageOf = (event) => {
  if (event.type === 'assistant/chunk' && event.data.chunk.type === 'usage') return event.data.chunk.usage
  if (event.type === 'assistant/message') return event.data.usage
  return undefined
}

/** Bill key: one bucket per (tariff, model) pair. */
const billKey = (tariff, model) => `${tariff}\u0000${model}`

/**
 * Fold one committed session event into the billing state.
 *
 * A step reports usage twice — an early `assistant/chunk` that survives a later
 * request failure, then the finalized `assistant/message` — so a repeated
 * report for the same (turn, step) REPLACES its predecessor rather than adding
 * to it, including when the message's own model differs from the request
 * header that preceded it.
 * @param {object} state - state covering all prior events.
 * @param {object} event - the next committed session event.
 * @returns {object} next state, or the same reference when the event is not ours.
 */
function foldEvent(state, event) {
  if (event.type === 'step/start') {
    return { ...state, step: { turn: event.data.turn, step: event.data.step, time: event.time } }
  }
  if (event.type === 'request/context') {
    const route = { model: event.data.model, provider: event.data.provider }
    if (state.route !== null && state.route.model === route.model && state.route.provider === route.provider) return state
    return { ...state, route }
  }
  if (event.type === 'request/header') {
    const model = event.data.header.config?.model
    if (typeof model !== 'string' || model === '') return state
    const route = { model, provider: event.data.header.config?.provider ?? state.route?.provider ?? '' }
    if (state.route !== null && state.route.model === route.model && state.route.provider === route.provider) return state
    return { ...state, route }
  }

  const usage = usageOf(event)
  if (usage === undefined) return state

  const { turn, step } = event.data
  // The message carries the model that actually answered; a chunk-only report
  // (a step whose request later failed) falls back to the last routed model.
  const source = event.type === 'assistant/message' ? event.data.message?.source : undefined
  const model = source?.kind === 'model' && typeof source.model === 'string' && source.model !== ''
    ? source.model
    : state.route?.model
  if (typeof model !== 'string' || model === '') return state

  // Dispatch time decides the tariff, not the time the answer finished: a
  // request sent one minute before the peak window opens is billed off-peak.
  const dispatchedAt = state.step !== null && state.step.turn === turn && state.step.step === step
    ? state.step.time
    : event.time
  const tariff = tariffAt(dispatchedAt)
  const sample = billedTokens(usage)
  const previous = state.last !== null && state.last.turn === turn && state.last.step === step ? state.last : null
  if (previous !== null
    && previous.key === billKey(tariff, model)
    && previous.sample.miss === sample.miss
    && previous.sample.hit === sample.hit
    && previous.sample.out === sample.out) {
    return state
  }

  const bills = { ...state.bills }
  if (previous !== null) {
    const held = bills[previous.key] ?? zero()
    bills[previous.key] = add(held, { miss: -previous.sample.miss, hit: -previous.sample.hit, out: -previous.sample.out }, -1)
  }
  const key = billKey(tariff, model)
  bills[key] = add(bills[key] ?? zero(), sample, 1)

  return {
    ...state,
    bills,
    last: { turn, step, key, sample },
    firstAt: state.firstAt ?? dispatchedAt,
    lastAt: dispatchedAt,
  }
}

/**
 * Project the billing state into the value the Web UI reads.
 *
 * `counterfactual` is what the same tokens would have cost billed entirely at
 * one tariff — the honest way to show what the time-of-use switchover, or a
 * cold cache, is worth on this session's actual traffic.
 * @param {object} state - the folded billing state.
 * @param {string} currency - `usd` or `cny`.
 * @returns {object} the wire value for the `costMeter` projection key.
 */
function view(state, currency) {
  const models = new Map()
  const byTariff = { flat: 0, offpeak: 0, peak: 0 }
  const totals = { miss: 0, hit: 0, out: 0 }
  const counterfactual = { flat: 0, offpeak: 0, peak: 0, noCache: 0 }
  const byBucket = { miss: 0, hit: 0, out: 0 }
  let cost = 0
  let requests = 0
  let unpricedRequests = 0

  for (const [key, tokens] of Object.entries(state.bills)) {
    if (tokens.requests === 0 && tokens.miss === 0 && tokens.hit === 0 && tokens.out === 0) continue
    const [tariff, model] = key.split('\u0000')
    const priced = isPriced(model)
    const split = bucketCostOf(tokens, model, tariff, currency)
    byBucket.miss += split.miss
    byBucket.hit += split.hit
    byBucket.out += split.out
    const billed = split.miss + split.hit + split.out
    const held = models.get(model) ?? { model, priced, miss: 0, hit: 0, out: 0, requests: 0, cost: 0 }
    models.set(model, {
      ...held,
      miss: held.miss + tokens.miss,
      hit: held.hit + tokens.hit,
      out: held.out + tokens.out,
      requests: held.requests + tokens.requests,
      cost: held.cost + billed,
    })
    totals.miss += tokens.miss
    totals.hit += tokens.hit
    totals.out += tokens.out
    requests += tokens.requests
    if (!priced) unpricedRequests += tokens.requests
    cost += billed
    byTariff[tariff] += billed
    for (const alternative of TARIFFS) counterfactual[alternative] += costOf(tokens, model, alternative, currency)
    // Every cache hit repriced as a miss: what the reuse was worth.
    counterfactual.noCache += costOf({ miss: tokens.miss + tokens.hit, hit: 0, out: tokens.out }, model, tariff, currency)
  }

  return {
    currency,
    cost: round(cost),
    requests,
    tokens: totals,
    byBucket: { miss: round(byBucket.miss), hit: round(byBucket.hit), out: round(byBucket.out) },
    byTariff: { flat: round(byTariff.flat), offpeak: round(byTariff.offpeak), peak: round(byTariff.peak) },
    counterfactual: {
      flat: round(counterfactual.flat),
      offpeak: round(counterfactual.offpeak),
      peak: round(counterfactual.peak),
      noCache: round(counterfactual.noCache),
    },
    models: [...models.values()]
      .map(entry => ({ ...entry, cost: round(entry.cost) }))
      .sort((left, right) => right.cost - left.cost || left.model.localeCompare(right.model)),
    unpricedRequests,
    ...state.firstAt === null ? {} : { firstAt: state.firstAt },
    ...state.lastAt === null ? {} : { lastAt: state.lastAt },
  }
}

/** Money carries eight decimals: a single cheap request is worth ~1e-6 and must not round to nothing. */
const round = amount => Math.round(amount * 1e8) / 1e8

/**
 * Structural check on the projection value, standing in for the Zod schema the
 * registry's typed contract names — the value is produced by {@link view} in
 * this same module, so this is a tripwire against a fold bug, not input parsing.
 */
const schema = {
  /**
   * Validate one projection value.
   * @param {unknown} value - the `view` output.
   * @returns {object} the same value when it holds.
   */
  parse(value) {
    const fail = (reason) => { throw new Error(`dsh-meter: malformed costMeter projection (${reason})`) }
    if (typeof value !== 'object' || value === null) fail('not an object')
    const money = (amount, field) => {
      if (typeof amount !== 'number' || !Number.isFinite(amount) || amount < 0) fail(`${field} is not a non-negative number`)
    }
    money(value.cost, 'cost')
    if (!Array.isArray(value.models)) fail('models is not an array')
    for (const entry of value.models) money(entry.cost, `models[${entry.model}].cost`)
    for (const key of ['miss', 'hit', 'out']) money(value.byBucket?.[key], `byBucket.${key}`)
    for (const key of ['flat', 'offpeak', 'peak']) money(value.byTariff?.[key], `byTariff.${key}`)
    for (const key of ['flat', 'offpeak', 'peak', 'noCache']) money(value.counterfactual?.[key], `counterfactual.${key}`)
    return value
  },
}

/* ------------------------------------------------------------------ *
 * Display helpers — shared so the dock line, the card, and any future
 * surface round money the same way.
 * ------------------------------------------------------------------ */

/**
 * Money at a fixed useful precision: four decimals under a unit (a whole
 * session is often worth less than one cent), two above it, none above 1000.
 * @param {number} amount - cost in currency units.
 * @param {string} currency - `usd` or `cny`.
 * @returns {string} display string with its symbol.
 */
function formatMoney(amount, currency) {
  const symbol = CURRENCY_SYMBOL[currency] ?? ''
  const magnitude = Math.abs(amount)
  if (magnitude >= 1000) return `${symbol}${Math.round(amount)}`
  if (magnitude >= 1) return `${symbol}${amount.toFixed(2)}`
  if (magnitude === 0) return `${symbol}0`
  if (magnitude < 0.0001) return `<${symbol}0.0001`
  return `${symbol}${amount.toFixed(4)}`
}

/**
 * Compact token count, matching the harness stats line: 517 / 12.2K / 1.2M.
 * @param {number} count - token count.
 * @returns {string} display string.
 */
function formatTokens(count) {
  const scaled = value => (value >= 100 ? String(Math.round(value)) : String(Math.round(value * 10) / 10))
  if (count < 1000) return String(Math.round(count))
  if (count < 1_000_000) return `${scaled(count / 1000)}K`
  return `${scaled(count / 1_000_000)}M`
}

/**
 * Coarse countdown for the tariff clock: 45s, 12m, 3h20m, 2d.
 * @param {number} ms - milliseconds remaining.
 * @returns {string} display string.
 */
function formatCountdown(ms) {
  const seconds = Math.max(0, Math.round(ms / 1000))
  if (seconds < 60) return `${seconds}s`
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes}m`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return hours < 10 && minutes % 60 !== 0 ? `${hours}h${minutes % 60}m` : `${hours}h`
  return `${Math.floor(hours / 24)}d`
}

/**
 * dsh-meter — browser half.
 *
 * One line under the composer, in the seat the harness reserves for ambient
 * conversation readouts, plus a detail card on hover or focus. The line
 * answers the three questions a time-of-use rate card creates: what has this
 * session cost, which tariff am I standing in, and when does it change.
 *
 * Money arrives finished from the `costMeter` session projection — this half
 * owns no price table and no fold. What it owns is the clock: the tariff
 * schedule is wall-clock state, invisible to a log-derived projection, so the
 * countdown and the day strip are computed here from the shared core.
 *
 * `scripts/build-client.mjs` inlines lib/core.js above this file and wraps
 * both in the module-loader factory; nothing here imports.
 */

/** Dictionary namespace owned by this plugin. */
const NS = 'costMeter'

const en = {
  'meter.flat': 'flat rate',
  'meter.peak': 'peak',
  'meter.offpeak': 'off-peak',
  'meter.switchIn': '{tariff} in {countdown}',
  'meter.timeOfUseIn': 'time-of-use in {countdown}',
  'meter.noRate': '{count} requests · no published rate',
  'meter.title': 'Session cost',
  'meter.requests': '{count} requests',
  'meter.requestOne': '1 request',
  'meter.tariffNow': 'Tariff · local',
  'meter.until': '{tariff} until {time}',
  'meter.cacheHits': 'cache hits',
  'meter.freshInput': 'fresh input',
  'meter.output': 'output',
  'meter.cacheSaved': 'Cache reuse saved {amount} — {percent}% of prompt tokens were hits.',
  'meter.cacheCold': 'No cache hits yet. A stable prompt prefix bills at {rate} of the miss rate.',
  'meter.ifPeak': 'Same tokens all-peak {peak}, all-off-peak {offpeak}.',
  'meter.ifNewRates': 'Under the rates starting {date}: {offpeak} off-peak, {peak} peak.',
  'meter.unpriced': '{count} requests on {models} have no published rate and are not counted.',
  'meter.source': 'Estimated from reported tokens at DeepSeek list prices. The invoice is authoritative.',
}

const zh = {
  'meter.flat': '统一价',
  'meter.peak': '高峰',
  'meter.offpeak': '空闲',
  'meter.switchIn': '{countdown}后转{tariff}',
  'meter.timeOfUseIn': '{countdown}后启用峰谷价',
  'meter.noRate': '{count} 次请求 · 无公开价格',
  'meter.title': '本会话花费',
  'meter.requests': '{count} 次请求',
  'meter.requestOne': '1 次请求',
  'meter.tariffNow': '时段价 · 本地时间',
  'meter.until': '{tariff}，{time} 结束',
  'meter.cacheHits': '缓存命中',
  'meter.freshInput': '未命中输入',
  'meter.output': '输出',
  'meter.cacheSaved': '缓存复用省下 {amount}——{percent}% 的输入命中缓存。',
  'meter.cacheCold': '尚无缓存命中。前缀稳定时命中价仅为未命中价的 {rate}。',
  'meter.ifPeak': '同样的 token 全高峰 {peak}，全空闲 {offpeak}。',
  'meter.ifNewRates': '{date} 起的新价：空闲 {offpeak}，高峰 {peak}。',
  'meter.unpriced': '{count} 次请求使用 {models}，无公开价格，未计入。',
  'meter.source': '按 DeepSeek 官方价目与上报 token 估算，实际以账单为准。',
}

const CSS = `
.dshMeterRoot{display:block;max-width:var(--dsh-chat-content-width);width:100%;margin:0 auto;box-sizing:border-box;
  padding:0 calc(var(--dsh-composer-side-clearance) + 16px) 2px;text-align:center;font-size:12px;line-height:20px;
  color:var(--dsw-alias-label-tertiary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dshMeterLine{display:inline-flex;align-items:center;gap:0;border-radius:6px;padding:0 6px;margin:0 -6px;
  cursor:default;outline:none;max-width:100%}
.dshMeterLine:hover,.dshMeterLine:focus-visible{background:var(--dsw-alias-interactive-bg-hover)}
.dshMeterLine:focus-visible{box-shadow:0 0 0 2px var(--dsw-alias-state-business-primary)}
.dshMeterCost{color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}
.dshMeterSep{color:var(--dsw-alias-separator-primary);margin:0 10px}
.dshMeterPeak{color:var(--dsw-alias-state-warn-primary)}
.dshMeterOffpeak{color:var(--dsw-alias-state-success-primary)}
.dshMeterFlat{color:var(--dsw-alias-label-tertiary)}

/* Panel material is the harness's own popover recipe (ContextMeter.module.css):
   a plugin surface should belong to the product, not announce itself. */
.dshMeterCard{position:fixed;z-index:100;width:328px;box-sizing:border-box;padding:14px 14px 12px;
  border:1px solid var(--dsw-alias-border-inverted);border-radius:12px;background:var(--dsw-specific-menu);
  box-shadow:var(--dsw-shadow-lv3);text-align:left;white-space:normal;
  max-height:calc(100vh - 96px);overflow-y:auto;
  color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px;cursor:default}
.dshMeterHead{display:flex;align-items:baseline;justify-content:space-between;gap:12px}
.dshMeterHeadLabel{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:20px}
.dshMeterTotal{color:var(--dsw-alias-label-primary);font-size:20px;line-height:26px;font-weight:600;
  font-variant-numeric:tabular-nums}
.dshMeterSub{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;margin-top:2px}
.dshMeterRule{height:1px;background:var(--dsw-alias-border-l1);margin:12px -14px}

.dshMeterStripHead{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}
.dshMeterStripNow{font-variant-numeric:tabular-nums}
/* Off-peak reads as quiet neutral and peak as the warm signal: the strip is
   there to show when the meter runs double, not to paint every hour. */
.dshMeterStrip{position:relative;display:flex;gap:2px;height:10px}
.dshMeterCell{flex:1;border-radius:2px;background:var(--dsw-alias-border-l3)}
.dshMeterCell[data-peak="1"]{background:var(--dsw-alias-state-warn-primary);opacity:.75}
.dshMeterNow{position:absolute;top:-3px;bottom:-3px;width:2px;border-radius:1px;
  background:var(--dsw-alias-label-primary);transform:translateX(-1px)}
.dshMeterTicks{position:relative;height:14px;margin-top:3px;color:var(--dsw-alias-label-caption);
  font-size:10px;line-height:14px;font-variant-numeric:tabular-nums}
.dshMeterTick{position:absolute;top:0;transform:translateX(-50%)}

.dshMeterRow{display:flex;align-items:baseline;justify-content:space-between;gap:10px;padding:2px 0}
.dshMeterRowLabel{color:var(--dsw-alias-label-tertiary)}
.dshMeterRowTokens{color:var(--dsw-alias-label-caption);font-variant-numeric:tabular-nums;
  margin-left:auto;padding-right:10px}
.dshMeterRowCost{color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}
.dshMeterModels{margin-top:6px;padding-top:6px;border-top:1px dashed var(--dsw-alias-border-l1)}
.dshMeterNote{color:var(--dsw-alias-label-caption);font-size:11px;line-height:16px;margin-top:6px}
.dshMeterNote:first-of-type{margin-top:10px}
.dshMeterFoot{color:var(--dsw-alias-label-caption);font-size:10px;line-height:15px;margin-top:10px;
  padding-top:8px;border-top:1px solid var(--dsw-alias-border-l1)}
@media (prefers-reduced-motion:no-preference){.dshMeterCard{animation:dshMeterIn 120ms ease-out}}
@keyframes dshMeterIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}
`

/** Inject the plugin stylesheet once, the way built harness bundles do. */
function installStyles() {
  if (typeof document === 'undefined') return
  const tagId = 'dsh-meter/meter.css'
  if (document.querySelector(`style[data-plugin-css="${tagId}"]`) !== null) return
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-meter'
  tag.dataset.pluginCss = tagId
  tag.textContent = CSS
  document.head.appendChild(tag)
}

/** Fill `{name}` placeholders; the fallback path when no locale service is installed. */
function fill(template, params) {
  let text = template
  for (const key of Object.keys(params ?? {})) text = text.split(`{${key}}`).join(String(params[key]))
  return text
}

/** Translate through the framework seat, falling back to this plugin's own English copy. */
function translator(t) {
  return (key, params) => {
    if (typeof t === 'function') {
      const translated = t(key, params)
      // A missing key echoes back as the key itself in the harness dictionaries.
      if (typeof translated === 'string' && translated !== key) return translated
    }
    return fill(en[key] ?? key, params)
  }
}

/** Model ids read as product names in a one-line summary: deepseek-v4-pro -> V4-Pro. */
function shortModel(model) {
  return model.replace(/^deepseek-/, '').replace(/(^|-)([a-z])/g, (_all, dash, letter) => dash + letter.toUpperCase())
}

/**
 * The 24 local-hour cells of the tariff day, each labelled from the UTC hour at
 * its midpoint so a half-hour timezone still lands in the right window.
 */
function localTariffCells(now) {
  const midnight = new Date(now)
  midnight.setHours(0, 0, 0, 0)
  const schedule = tariffSchedule()
  const cells = []
  for (let hour = 0; hour < 24; hour++) {
    const middle = new Date(midnight.getTime() + (hour + 0.5) * 3_600_000)
    cells.push(schedule[middle.getUTCHours()])
  }
  return { midnight: midnight.getTime(), cells }
}

/**
 * Local-clock label for an instant. A change that is not today carries its date:
 * before the switchover the next change is more than a day out, and a bare
 * `09:00` would read as this morning.
 */
function clockLabel(epochMs, now) {
  const date = new Date(epochMs)
  const time = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
  const sameDay = new Date(now).toDateString() === date.toDateString()
  return sameDay ? time : `${date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} ${time}`
}

/**
 * The rect the card is anchored above: the whole composer stack, not this one
 * line. The dock sits under the composer card, so a card opening upward from
 * the line itself would land on top of the input the user is about to type in.
 * The stack is the outermost ancestor that still ends where this line ends.
 */
function anchorRect(element) {
  // The scrollport and the app frame also end at the viewport bottom, so the
  // walk stops at the first ancestor taller than a composer strip could be
  // rather than latching onto the whole page.
  const STACK_HEIGHT_LIMIT = 400
  let rect = element.getBoundingClientRect()
  let node = element.parentElement
  for (let depth = 0; depth < 6 && node !== null; depth++) {
    const candidate = node.getBoundingClientRect()
    if (candidate.height > STACK_HEIGHT_LIMIT) break
    if (candidate.height > 0 && Math.abs(candidate.bottom - rect.bottom) <= 16) rect = candidate
    node = node.parentElement
  }
  return rect
}

/** The tariff day strip: 24 local hours coloured by window, with a live now marker. */
function TariffStrip({ now }) {
  const { midnight, cells } = localTariffCells(now)
  const dayFraction = Math.min(1, Math.max(0, (now - midnight) / 86_400_000))
  return React.createElement(
    'div',
    null,
    React.createElement(
      'div',
      { className: 'dshMeterStrip' },
      cells.map((tariff, hour) =>
        React.createElement('div', {
          key: hour,
          className: 'dshMeterCell',
          'data-peak': tariff === 'peak' ? '1' : '0',
        })),
      React.createElement('div', {
        className: 'dshMeterNow',
        style: { left: `${dayFraction * 100}%` },
      }),
    ),
    React.createElement(
      'div',
      { className: 'dshMeterTicks' },
      [0, 6, 12, 18, 24].map(hour =>
        React.createElement('span', {
          key: hour,
          className: 'dshMeterTick',
          style: {
            left: `${(hour / 24) * 100}%`,
            transform: hour === 0 ? 'none' : hour === 24 ? 'translateX(-100%)' : 'translateX(-50%)',
          },
        }, hour === 24 ? '24' : String(hour).padStart(2, '0'))),
    ),
  )
}

/** One breakdown row: what was billed, how many tokens, and what it cost. */
function BreakdownRow({ label, tokens, cost, currency }) {
  return React.createElement(
    'div',
    { className: 'dshMeterRow' },
    React.createElement('span', { className: 'dshMeterRowLabel' }, label),
    React.createElement('span', { className: 'dshMeterRowTokens' }, `${formatTokens(tokens)} tok`),
    React.createElement('span', { className: 'dshMeterRowCost' }, formatMoney(cost, currency)),
  )
}

/** The hover card: the total, the tariff clock, where the money went, and what it could have been. */
function MeterCard({ value, now, t, position }) {
  const currency = value.currency
  const clock = nextTariffChange(now)
  const tariffName = t(`meter.${clock.tariff === 'flat' ? 'flat' : clock.tariff}`)
  const promptTokens = value.tokens.hit + value.tokens.miss
  const hitShare = promptTokens === 0 ? 0 : Math.round((value.tokens.hit / promptTokens) * 100)
  const saved = value.counterfactual.noCache - value.cost
  const models = value.models.map(entry => shortModel(entry.model)).join(', ')

  const notes = []
  if (value.tokens.hit > 0) {
    notes.push(t('meter.cacheSaved', { amount: formatMoney(saved, currency), percent: hitShare }))
  } else if (promptTokens > 0) {
    notes.push(t('meter.cacheCold', { rate: '1/50' }))
  }
  if (clock.tariff === 'flat') {
    notes.push(t('meter.ifNewRates', {
      date: new Date(TIME_OF_USE_FROM).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }),
      offpeak: formatMoney(value.counterfactual.offpeak, currency),
      peak: formatMoney(value.counterfactual.peak, currency),
    }))
  } else {
    notes.push(t('meter.ifPeak', {
      peak: formatMoney(value.counterfactual.peak, currency),
      offpeak: formatMoney(value.counterfactual.offpeak, currency),
    }))
  }
  if (value.unpricedRequests > 0) {
    notes.push(t('meter.unpriced', {
      count: value.unpricedRequests,
      models: value.models.filter(entry => !entry.priced).map(entry => entry.model).join(', '),
    }))
  }

  return React.createElement(
    'div',
    { className: 'dshMeterCard', style: position, role: 'tooltip' },
    React.createElement(
      'div',
      { className: 'dshMeterHead' },
      React.createElement('span', { className: 'dshMeterHeadLabel' }, t('meter.title')),
      React.createElement('span', { className: 'dshMeterTotal' }, formatMoney(value.cost, currency)),
    ),
    React.createElement('div', { className: 'dshMeterSub' },
      `${value.requests === 1 ? t('meter.requestOne') : t('meter.requests', { count: value.requests })}`
      + `${models === '' ? '' : ` · ${models}`}`),
    React.createElement('div', { className: 'dshMeterRule' }),
    React.createElement(
      'div',
      { className: 'dshMeterStripHead' },
      React.createElement('span', { className: 'dshMeterHeadLabel' }, t('meter.tariffNow')),
      React.createElement(
        'span',
        { className: `dshMeterStripNow dshMeter${clock.tariff === 'flat' ? 'Flat' : clock.tariff === 'peak' ? 'Peak' : 'Offpeak'}` },
        t('meter.until', { tariff: tariffName, time: clockLabel(clock.at, now) }),
      ),
    ),
    React.createElement(TariffStrip, { now }),
    React.createElement('div', { className: 'dshMeterRule' }),
    React.createElement(BreakdownRow, {
      label: t('meter.cacheHits'), tokens: value.tokens.hit, cost: value.byBucket.hit, currency,
    }),
    React.createElement(BreakdownRow, {
      label: t('meter.freshInput'), tokens: value.tokens.miss, cost: value.byBucket.miss, currency,
    }),
    React.createElement(BreakdownRow, {
      label: t('meter.output'), tokens: value.tokens.out, cost: value.byBucket.out, currency,
    }),
    // Per-model rows only earn their space once the session actually used more
    // than one model; the header already names a single one.
    value.models.length < 2
      ? null
      : React.createElement(
        'div',
        { className: 'dshMeterModels' },
        value.models.map(entry => React.createElement(BreakdownRow, {
          key: entry.model,
          label: shortModel(entry.model),
          tokens: entry.miss + entry.hit + entry.out,
          cost: entry.cost,
          currency,
        })),
      ),
    notes.map((note, index) => React.createElement('div', { key: index, className: 'dshMeterNote' }, note)),
    React.createElement('div', { className: 'dshMeterFoot' }, t('meter.source')),
  )
}

/**
 * The composer-dock readout: cost, the tariff standing over it, and the
 * countdown to the next change.
 */
function CostMeterLine({ useProjection, t: translate }) {
  const value = useProjection('costMeter')
  const t = translator(translate)
  const [now, setNow] = React.useState(() => Date.now())
  const [card, setCard] = React.useState(null)
  const anchor = React.useRef(null)
  const closeTimer = React.useRef(null)

  // The countdown is the reason this surface exists, so it ticks while mounted.
  // Half-minute cadence keeps a minute-resolution readout honest without
  // rendering on a timer the eye can see.
  React.useEffect(() => {
    const id = setInterval(() => { setNow(Date.now()) }, 30_000)
    return () => { clearInterval(id) }
  }, [])

  const place = React.useCallback(() => {
    const element = anchor.current
    if (element === null) return
    const rect = anchorRect(element)
    const width = 328
    const left = Math.min(Math.max(8, rect.left + rect.width / 2 - width / 2), window.innerWidth - width - 8)
    setCard({ left, bottom: Math.max(8, window.innerHeight - rect.top + 8) })
  }, [])

  React.useEffect(() => {
    if (card === null) return
    const reposition = () => { place() }
    window.addEventListener('scroll', reposition, true)
    window.addEventListener('resize', reposition)
    return () => {
      window.removeEventListener('scroll', reposition, true)
      window.removeEventListener('resize', reposition)
    }
  }, [card === null, place])

  React.useEffect(() => () => { if (closeTimer.current !== null) clearTimeout(closeTimer.current) }, [])

  const open = () => {
    if (closeTimer.current !== null) { clearTimeout(closeTimer.current) ; closeTimer.current = null }
    setNow(Date.now())
    place()
  }
  // A grace delay lets the pointer cross the gap between line and card.
  const close = () => {
    if (closeTimer.current !== null) clearTimeout(closeTimer.current)
    closeTimer.current = setTimeout(() => { setCard(null) ; closeTimer.current = null }, 120)
  }

  if (value === undefined || value.requests === 0) return null

  const clock = nextTariffChange(now)
  const tariffClass = clock.tariff === 'peak' ? 'dshMeterPeak' : clock.tariff === 'offpeak' ? 'dshMeterOffpeak' : 'dshMeterFlat'
  const countdown = formatCountdown(clock.at - now)
  const trailing = clock.tariff === 'flat'
    ? t('meter.timeOfUseIn', { countdown })
    : t('meter.switchIn', { tariff: t(`meter.${clock.next}`), countdown })
  const separator = () => React.createElement('span', { className: 'dshMeterSep', 'aria-hidden': 'true' }, '|')

  return React.createElement(
    'div',
    { className: 'dshMeterRoot' },
    React.createElement(
      'span',
      {
        className: 'dshMeterLine',
        ref: anchor,
        tabIndex: 0,
        onMouseEnter: open,
        onMouseLeave: close,
        onFocus: open,
        onBlur: close,
      },
      value.unpricedRequests === value.requests
        ? React.createElement('span', { className: 'dshMeterCost' }, t('meter.noRate', { count: value.requests }))
        : React.createElement('span', { className: 'dshMeterCost' }, formatMoney(value.cost, value.currency)),
      separator(),
      React.createElement('span', { className: tariffClass }, t(`meter.${clock.tariff === 'flat' ? 'flat' : clock.tariff}`)),
      separator(),
      React.createElement('span', null, trailing),
      // The card is a React child of this span but a DOM child of body, so
      // React's enter/leave traversal already counts it as inside: one pair of
      // handlers covers the line and the card, and the pointer can cross the
      // gap between them without closing.
      card === null
        ? null
        : ReactDOM.createPortal(React.createElement(MeterCard, { value, now, t, position: card }), document.body),
    ),
  )
}

/** Slot and locale services this surface needs. */
const inject = ['slots']

/**
 * Client plugin body: one entry in the composer dock, ordered after the
 * harness stats line rather than replacing it.
 * @param {object} ctx - client root context.
 */
function apply(ctx) {
  installStyles()
  const locale = ctx.get('locale')
  if (locale !== undefined) ctx.effect(() => locale.register(NS, { zh, en }), 'dsh-meter: dictionaries')
  ctx.slots.inject('conversation.composer.dock', () => ctx.slots.register(
    { name: 'conversation.composer.dock', id: 'cost-meter', order: 10, locale: NS },
    CostMeterLine,
  ))
}

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
