#!/usr/bin/env node
/**
 * Compose lib/client.js — the browser bundle the harness serves at
 * /plugins/dsh-meter/client.js — from lib/core.js and src/ui.js.
 *
 * The bundle format is the module loader's: one `window.__ModuleLoader__.load`
 * call whose factory receives `require`, assigns `exports.apply` / `.inject`,
 * and returns `module.exports`. Both source files are plain ES modules with no
 * imports, so composing them is stripping the `export` keyword and
 * concatenating — no bundler, no toolchain, no install-time build.
 *
 * This exists so the rate card lives in exactly one file. A cost plugin that
 * keeps a second copy of the price table for its UI is one upstream change away
 * from showing two different numbers for the same session.
 *
 * Usage: `node scripts/build-client.mjs` writes the bundle;
 *        `node scripts/build-client.mjs --check` fails when it is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Strip ES module syntax: these files have no imports, so only `export` needs removing. */
const inline = (path) => {
  const source = readFileSync(join(root, path), 'utf8')
  if (/^\s*import\s/m.test(source)) throw new Error(`build-client: ${path} must not import — the bundle has no module graph`)
  return source.replace(/^export (const|function|let) /gm, '$1 ').replace(/^export /gm, '')
}

const bundle = `// GENERATED by scripts/build-client.mjs — edit lib/core.js or src/ui.js instead.
window.__ModuleLoader__.load({
  id: "dsh-meter",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const React = require("react");
    const ReactDOM = require("react-dom");

${inline('lib/core.js').trimEnd()}

${inline('src/ui.js').trimEnd()}

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
`

const target = join(root, 'lib/client.js')
if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(target, 'utf8')
    } catch {
      return ''
    }
  })()
  if (current !== bundle) {
    process.stderr.write('build-client: lib/client.js is stale — run `node scripts/build-client.mjs`\n')
    process.exit(1)
  }
  process.stdout.write('build-client: lib/client.js is in sync\n')
} else {
  writeFileSync(target, bundle)
  process.stdout.write(`build-client: wrote lib/client.js (${bundle.length} bytes)\n`)
}
